<?php

namespace Database\Factories;

use App\Models\FormBuilder;
use Illuminate\Database\Seeder;

class FormBuilderSeeder extends Seeder
{
public function run()
{
    // Truncar la tabla users
    FormBuilder::truncate();

    FormBuilder::create(
            [
                'name' => 'rut',
                'label' => 'RUT',
                'type' => 'text',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'endpoint' => null,
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 1,
            ]);
        FormBuilder::create(
            [
                'name' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 2,
            ]);
        FormBuilder::create(
            [
                'name' => 'apellidos',
                'label' => 'Apellidos',
                'type' => 'text',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 3,
            ]);

        FormBuilder::create(
            [
                'name' => 'calles_id',
                'label' => 'Calles',
                'type' => 'select',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 4,
            ]);

        FormBuilder::create(
            [
                'name' => 'ciudad',
                'label' => 'Ciudad',
                'type' => 'text',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 5,
            ]);

        FormBuilder::create(
            [
                'name' => 'comunidad_lgbtq',
                'label' => 'Comunidad LGBTQ',
                'type' => 'switch',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 6,
            ]);

        FormBuilder::create(
            [
                'name' => 'credencial_discapacidad',
                'label' => 'Credencial Discapacidad',
                'type' => 'switch',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 7,
            ]);

        FormBuilder::create(
            [
                'name' => 'direccion',
                'label' => 'Dirección',
                'type' => 'text',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 8,
            ]);

        FormBuilder::create(
            [
                'name' => 'donante',
                'label' => 'Donante',
                'type' => 'switch',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 9,
            ]);

        FormBuilder::create(
                [
                    'name' => 'fecha_nacimiento',
                    'label' => 'Fecha de nacimiento',
                    'type' => 'date',
                    'required' => true,
                    'clearable' => true,
                    'variant' => 'underlined',
                    'cols' => 12,
                    'row' => 1,
                    'md' => 4,
                    'sm' => 2,
                    'order' => 10,
                ]);

        FormBuilder::create(
            [
                'name' => 'edad',
                'label' => 'Edad',
                'type' => 'number',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 11,
            ]);

        FormBuilder::create(
            [
                'name' => 'email',
                'label' => 'Email',
                'type' => 'email',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 12,
            ]);

        FormBuilder::create(
            [
                'name' => 'estado_civil_id',
                'label' => 'Estado Civil',
                'type' => 'select',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 13,
            ]);
        
        FormBuilder::create(
            [
                'name' => 'genero_id',
                'label' => 'Género',
                'type' => 'select',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 14,
            ]);

        FormBuilder::create(
            [
                'name' => 'grupo_sanguineo_id',
                'label' => 'Grupo Sanguíneo',
                'type' => 'select',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 15,
            ]);

        FormBuilder::create(
            [
                'name' => 'nacionalidad_id',
                'label' => 'Nacionalidad',
                'type' => 'select',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 16,
            ]);

        FormBuilder::create(
            [
                'name' => 'nivel_instruccion_id',
                'label' => 'Nivel de instrucción',
                'type' => 'select',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 17,
            ]);

        FormBuilder::create(
            [
                'name' => 'ocupacion',
                'label' => 'Ocupación',
                'type' => 'text',
                'required' => true,
                'clearable' => true,
                'variant' => 'underlined',
                'cols' => 12,
                'row' => 1,
                'md' => 4,
                'sm' => 2,
                'order' => 18,
            ]);

            /* 
            {
                name: "apellidos_responsable",
                label: "Apellidos Responsable",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            
            {
                name: "calles_responsable_id",
                label: "Calles Responsable",
                type: "select",
                required: false,
                clearable: true,
                variant: "underlined",
                items: [],
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "ciudad_responsable",
                label: "Ciudad Responsable",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            
            {
                name: "comunidad_lgbtq_responsable",
                label: "Comunidad LGBTQ Responsable",
                type: "switch",
                color: "green-darken-3",
                inset: true,
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "credencial_discapacidad_responsable",
                label: "Credencial Discapacidad Responsable",
                type: "switch",
                color: "green-darken-3",
                inset: true,
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            
            {
                name: "direccion_responsable",
                label: "Dirección Responsable",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            
            {
                name: "donante_responsable",
                label: "Donante Responsable",
                type: "switch",
                required: false,
                color: "green-darken-3",
                inset: true,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
           
            {
                name: "edad_responsable",
                label: "Edad Responsable",
                type: "number",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            
            {
                name: "email_responsable",
                label: "Email Responsable",
                type: "email",
                inputType: "email",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            
            {
                name: "establecimiento_educacional_id",
                label: "Establecimiento Educacional",
                type: "select",
                inputType: "email",
                required: false,
                clearable: true,
                items: endpoints.establecimientos_educacionales,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "estado_civil_id",
                label: "Estado Civil ID",
                type: "select",
                required: false,
                clearable: true,
                items: endpoints.estados_civiles,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "estado_civil_responsable_id",
                label: "Estado Civil Responsable ID",
                type: "select",
                required: false,
                clearable: true,
                items: ["Soltero", "Casado", "Divorciado"],
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "fecha_nacimiento_responsable",
                label: "Fecha Nacimiento Responsable",
                type: "text",
                inputType: "date",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "fecha_nacimiento",
                label: "Fecha Nacimiento",
                type: "text",
                inputType: "date",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "genero_id",
                label: "Género ID",
                type: "select",
                required: false,
                clearable: true,
                items: ["Masculino", "Femenino", "Otro"],
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "genero_responsable_id",
                label: "Género Responsable ID",
                type: "select",
                required: false,
                clearable: true,
                items: ["Masculino", "Femenino", "Otro"],
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "grupo_sanguineo_id",
                label: "Grupo Sanguíneo ID",
                type: "select",
                required: false,
                clearable: true,
                items: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"],
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "grupo_sanguineo_responsable_id",
                label: "Grupo Sanguíneo Responsable ID",
                type: "select",
                required: false,
                clearable: true,
                items: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"],
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "nacionalidad_id",
                label: "Nacionalidad",
                type: "select",
                items: [],
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "nacionalidad_responsable_id",
                label: "Nacionalidad Responsable ID",
                type: "select",
                items: [],
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "nivel_instruccion_id",
                label: "Nivel Instrucción ID",
                type: "text",
                items: [],
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "nivel_instruccion_responsable_id",
                label: "Nivel Instrucción Responsable ID",
                type: "select",
                items: [],
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "nombre_responsable",
                label: "Nombre Responsable",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
    
            {
                name: "ocupacion_responsable",
                label: "Ocupación Responsable",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "ocupacion",
                label: "Ocupación",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "parentesco_responsable",
                label: "Parentesco Responsable",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
    
            {
                name: "pertenece_pie",
                label: "Pertenece PIE",
                type: "switch",
                required: false,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "prevision_id",
                label: "Previsión",
                type: "select",
                items: [],
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "prevision_responsable_id",
                label: "Previsión Responsable ID",
                type: "select",
                items: [],
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "profesor",
                label: "Profesor",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "pueblo_originario_id",
                label: "Pueblo Originario ID",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "pueblo_originario_responsable_id",
                label: "Pueblo Originario Responsable ID",
                type: "select",
                items: [],
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "religion_id",
                label: "Religión ID",
                type: "select",
                items: [],
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "religion_responsable_id",
                label: "Religión Responsable ID",
                type: "select",
                items: [],
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "rut_responsable",
                label: "RUT Responsable",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
    
            {
                name: "telefono_responsable",
                label: "Teléfono Responsable",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 2,
            },
            {
                name: "telefono1",
                label: "Teléfono 1",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },
            {
                name: "telefono2",
                label: "Teléfono 2",
                type: "text",
                required: false,
                clearable: true,
                variant: "underlined",
                cols: 12,
                md: 4,
                sm: 2,
                row: 1,
            },    */         
}
}