[Scia Reto](https://sciareto.org) mind map
> __version__=`1.1`,showJumps=`true`
---

# Root topicsqs
> borderColor=`#00FF00`,fillColor=`#FFFF00`,mmd.emoticon=`apple`,textColor=`#000000`


## sqsqsq

### Cat \!A
> fillColor=`#404040`,textColor=`#FFFFFF`,topicLinkUID=`18E2B117BECA`

- TOPIC
<pre>18E2B11C167A</pre>

## AAA

### xaxax

### xax
> topicLinkUID=`18E2B11C167A`

